[AZURE]
TENANT_ID = ""
CLIENT_ID = ""
CLIENT_SECRET = ""
RESOURCE_GROUP = ""
LOCATION = ""
NAME = ""
SUBSCRIPTION_ID = ""

[API_KEYS]
IBMQ = ""
NASDAQ = ""

[DATABASE]
USE_DB = true
SQLITE_URL = "sqlite:///./qupo_backend/db/finance.db"