name: Test & Build Qupo
on:
  push:
    branches:
      - main
      - gh_actions
  release:
    types: [published]

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  build:
    runs-on: ubuntu-latest
    needs: []
    strategy:
      matrix:
        project: [frontend, api]
        include:
          - project: frontend
            image_name: kfwopensource/qupo-frontend
          - project: api
            image_name: kfwopensource/qupo-api
    defaults:
      run:
        working-directory: ${{ matrix.project }}

    env:
      GITHUB_PR_NUMBER: ${{ github.event.number}}
      GITHUB_BASE_REF: ${{ github.base_ref}}
      GITHUB_HEAD_REF: ${{ github.head_ref}}
      GITHUB_REF_NAME: ${{ github.ref_name}}
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME}}
      DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD}}
      IMAGE_NAME: ${{ matrix.image_name}}

    steps:
      - uses: actions/checkout@v3
      - uses: docker-practice/actions-setup-docker@master
      - uses: ./.github/workflows/build

  deployment:
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - name: Trigger Deployment
        run: curl -sX POST -F token=$WEBHOOK_TOKEN
          -F ref=main
          -F "variables[GITHUB_HEAD_BRANCH]=$GITHUB_HEAD_BRANCH"
          -F "variables[GITHUB_BASE_BRANCH]=$GITHUB_BASE_BRANCH"
          -F "variables[GITHUB_REF_NAME]=$GITHUB_REF_NAME"
          -F "variables[GITHUB_RUN_ID]=$GITHUB_RUN_ID"
          -F "variables[GITHUB_EVENT_NAME]=$GITHUB_EVENT_NAME-$GITHUB_BASE_BRANCH"
          -F "variables[GITHUB_PULL_REQUEST]=$GITHUB_PR_NUMBER"
          -F "variables[GITHUB_REPOSITORY]=$GITHUB_REPOSITORY"
          $WEBHOOK_URL > /dev/null
        shell: bash
